[project]
name = "simba"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "easy-udp>=0.1.10",
    "loguru>=0.7.3",
    "polars>=1.36.1",
    "rich>=14.2.0",
]
