[project]
name = "simba"
version = "2.0.0"
description = "Rewrite after lessons learned"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "loguru>=0.7.3",
    "polars>=1.38.1",
    "pydantic>=2.12.5",
    "rich>=14.2.0",
]

[tool.uv]
package = true
