services:
  simba:
    container_name: simba
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes: ['../:/home/simba/simba']
    network_mode: host
    ports: ['20127:20127']
    develop:
      watch:
        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
